version: 2
project_name: runware-cli

builds:
  - main: ./cmd/runware
    binary: runware
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "runware_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

homebrew_casks:
  - name: runware
    homepage: https://runware.ai
    description: A command-line tool for interacting with the Runware inference API.
    license: MIT
    url:
      verified: github.com/Runware/runware-cli/releases/download
    repository:
      owner: Runware
      name: homebrew-tap
    # TODO(dr): remove when we have Apple Developer ID approved.
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runware"]
          end

scoops:
  - repository:
      owner: Runware
      name: scoop-bucket
    directory: bucket
    homepage: https://runware.ai
    description: A command-line tool for interacting with the Runware inference API.
    license: MIT
