[changelog]
header = ""
body = """
{% if version %}\
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% if commits | filter(attribute="group", value="Features") | length > 0 %}
### Features
{% for commit in commits | filter(attribute="group", value="Features") %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/runware/runware-cli/commit/{{ commit.id }}))
{%- endfor %}
{% endif %}\
{% if commits | filter(attribute="group", value="Bug Fixes") | length > 0 %}
### Bug Fixes
{% for commit in commits | filter(attribute="group", value="Bug Fixes") %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/runware/runware-cli/commit/{{ commit.id }}))
{%- endfor %}
{% endif %}\
{% if commits | filter(attribute="group", value="Performance") | length > 0 %}
### Performance
{% for commit in commits | filter(attribute="group", value="Performance") %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/runware/runware-cli/commit/{{ commit.id }}))
{%- endfor %}
{% endif %}\
{% if commits | filter(attribute="group", value="Other") | length > 0 %}
### Other
{% for commit in commits | filter(attribute="group", value="Other") %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/runware/runware-cli/commit/{{ commit.id }}))
{%- endfor %}
{% endif %}\
{% endif %}
"""
trim = false
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^docs", skip = true },
  { message = "^test", skip = true },
  { message = "^ci", skip = true },
  { message = "^chore", skip = true },
  { message = "^build", skip = true },
  { message = "^refactor", skip = true },
  { message = "^.*", group = "Other" },
]
protect_breaking_commits = false
filter_commits = true
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
ignore_commit_message = []
